sudo: required
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
  chrome: stable
language: ruby
rvm:
  - 2.6.3
script:
  - bundle install --jobs 3 --retry 3
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - xvfb