language: ruby
rvm:
  - 2.6.3
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec